{% set name = "vsce" %}
{% set version = "2.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: 8fb8ae947be46cf263f7b47db8cc76748d474b2c8d23a2e1253c5479f5f45ea2

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
    - {{ compiler('c') }}    # [ppc64le]
    - {{ compiler('cxx') }}  # [ppc64le]
    - pkg-config             # [ppc64le]
    - make                   # [ppc64le]
  host:
    - nodejs
    - yarn
    - glib                   # [ppc64le]
    - libsecret              # [ppc64le]
  run:
    - nodejs

test:
  commands:
    - vsce --help

about:
  home: https://github.com/microsoft/vscode-vsce
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: VS Code Extension Manager

extra:
  recipe-maintainers:
    - xhochy
