{% set name = "vsce" %}
{% set version = "2.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: 7ca80c7e117973ca4ca6b4bb0894de6d8b76bfa5758aa2a93de206a263159f6d

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
    - {{ compiler('c') }}    # [ppc64le]
    - {{ compiler('cxx') }}  # [ppc64le]
    - pkg-config             # [ppc64le]
    - make                   # [ppc64le]
  host:
    - nodejs
    - yarn
    - glib                   # [ppc64le]
    - libsecret              # [ppc64le]
  run:
    - nodejs

test:
  commands:
    - vsce --help

about:
  home: https://github.com/microsoft/vscode-vsce
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: VS Code Extension Manager

extra:
  recipe-maintainers:
    - xhochy
