{% set name = "vsce" %}
{% set version = "1.96.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: 1c2094196f6cb792b887704639413ae42fc330441cbbc5f06f82a0d82a655166

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - vsce --help

about:
  home: https://github.com/microsoft/vscode-vsce
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: VS Code Extension Manager

extra:
  recipe-maintainers:
    - xhochy
