{% set name = "vsce" %}
{% set version = "1.96.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: c8814943b3f39b6b4662e75fdb2dd630c6c120c13590db3ed12d30bddc9d1973

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - nodejs
    - yarn
  run:
    - nodejs

test:
  commands:
    - vsce --help

about:
  home: https://github.com/microsoft/vscode-vsce
  license: MIT
  license_file:
    - LICENSE
    - ThirdPartyLicenses.txt
  summary: VS Code Extension Manager

extra:
  recipe-maintainers:
    - xhochy
